service_name: wsl

targetEnv: test
targetNS: test

architecture:
  http_server_type: openresty   # apache2 | openresty are supported

targetImage: "registry.workstation.co.uk/webimpetus"
targetImageTag: "latest"

safeSealedSecret: AgA5nf+64iqFzTYBre3x3zwoEQ4TBEzAzBXNGakqTqAIJmVQtNWogT89Eo9OQ/m5egBl29+JLYWlHyllaRPMZinxl0i5zQAEjZE0c2sbSl79emO3vnRsXDHnf3sQNxBg+KNchgSWDlzP2Rfq1Rxe5Xf7NABvFs0A28UTAXnalzG3p3+/qcfBBtXcdQ/dnK8qTFZv2I7Y6zrQxdXxtLsCNOQJCtPBW8vNyYdQLXUYhtx7XvY9AFgM1PHUZjp78OHiUOqwQaTC45xm2DoWSAOSWtJcOOpyHJ9iRlSZbCgmCx+lIY9Kl6ikbNtwluHOSPVCVPmVm6W55tSRT3imCJw1JUuilF5vtgJ4B7Lo0t9t2rLTmpRStlWGV8AIA11IeMLOOsvlqPHyKAA5NwN2MyspovLU+GzPWsLR+LAIOL6fBNAyN8n32qrs6fdnt+i/nD1dO3wKyywItQuShdGNXjY6bI/EvVR01gVe4/+jUc1ZE8l9F7spRA36HUFk+M24qnF2HiQursRtK29cIv1zSw0zH+bZ/52+1qAPv3XVy7ToiuqbJXM3almytCbyXDa5F04Ui1Mhpk/59LY0F6A+hiDVqg2iDZPlDYP7XorFl34muxcJBME8tSlt5ZnnrRDDbZnot4S4URYmot4OlJRGJ1L1IQYxcm7n/c2ctiD2b3kX8fFdVcDJy431AlJI+X2DtoBSYwA=

serviceAccount:
  # Specifies whether a service account should be created
  create: true
# ports
svcAccessPort: 31179

# mysql / mariadb
db:
    hostname: AgB3QTDKpsrr2Z0COCN9mGlaNGvSUUbRT3e/wEtuTanz20125AosVJT5CdA7eLM4KQNw43t6sG7pdimSACu+3tFq7CD3M2z35T065eaYbU7SBqxFsSqLTtn9vZ0FESqkExUJSE2FPSw4S4pShnGZhG8AGiyYWFAL8O0TVEW2TjfbjpXQST7KEWD7EDd0HOP+iwuuKTGx7rXHKpF6J4Zn0tmpf648r79guJx1ZpKK4fSE4W67dfUAwRZQU3b6VSe4nwajYqyFtTZkleskhSX0OHuvi2wSu4AO7sJxjyABbEaftFJassrWTMB97bTKDUB12JLad4ekDxu7FupxzJzt8zQb7lWxjifISGDsTP6xmgWLAFun8w+tP552UWkLWwXskHvK2+9CAxJxQfwR390DyrlRlszg+byBEDgOBvTEO+f32V54xsCXVzjCn20YnIFWMHMYUy1JbNwJ87KldQiGRc5uxOpd/9v5vYMiDBrMEFApKzKkvF02ZbCOw6oM3SUcrNxlWkYZqiQN38Zjhasxw3pERvJC+cswftfaZlLGyHLH+RfHEr7IXEHPvqDFDPCpmL0t/IFXAXPIHP9BtLvl+BR9d12mQ453wu+wzaFFmijizMbUjnqtI+1cnRJC8Yt7sp3N16lxK7x257QinTh4yprpN8B7hj+Pe4fYX1AnwVTcZOnsLSSHGLtpF2AUUHMIgkPiup76pTbf5fevImioY9I4fD36btUo
    password: AgBzUOeZXh+ChIJ+SmhNTstXbUD1CGiUmi2O4q+0q77HoNyv6R2axEofOg55XxDNtiooNMWsvRyVVmwuPM9ReGFawDMWuUkskWlRAj2HBod72SmqPblB/Kfjin0XmK0OTXF4nNmVtNA7HyQN3dj6IMPV0uVawLiQHL/QE3WZ1HEfTi4SWn/JKxu1dduj6O4L4KlwpeDw1HUpBt1HN3RCEM/hF9/mZwPW3tq7Nf5AfP08cNwXyGQJBhUk6V3ZPPjn4Y0iqcFxZePO5Lkz2aHDnRu3k7aGzZGZFdTdcZ1gpgwbrHK5ucDZDKj1yqyik/rSuXCV+nqEsBSc+m4reHDjWTM6s5A/w1Y7GlfuX+JcH1Ya022vp9sTfEgdsW2SqUpCSDTzVlgs0IWxmjckUfvAq2eLev2jS8g1HR5poxSeHL8dgtysCAM5SEn2lFMzNftmTWodq5j8mxsn8pO5+fm6D1NFjymNGu1Ef7def91S8G07wYJkRGztXunjHZP7F73vc9HI3fjIL1ZQtZooLb0DnHtnrRgm60pse5ZvSwr/xDC2gwK/ZwnYaRAhQwGpLdT+MJ6pLK5JhSKwYCS9D0qIIiKpTgiISYSxulZODNCm8cB3INXhJIufHGAcidYJ5Es0wuBd8+OyqPPp3LmUU/ctqDFmZh1edj3XC1LfMaUZ26RSu1Lc5MDjCa4nu6EK0Z/ghUn9hW4lvFSB2Y5JIwc=
    port: AgA9SLeBRx/1u/cmk9AxtMt4NH+bJe2cn9dzmhelo3h0Yx4HVT1q0tBPY6c2tmxnZ85zFafWUfNnChqeTw5RqR2wABhiKbha1ET3vm7zvPnoXcMP8Dqlbkk5hJADnUD5q/3P7Qggk87vTgYgKxWMOQYUePvok/SQJvl27L3p6ucTpEcq2dcvJpQ7ocOJS8ahxCDwPAamiJIFu5t88DYzCVMJ72x/aMegp/Hc+wW8MD3OKX+F9Dx9IxusTJ+pDWyhYQYlWv2S6Y6J3B6lgq6Zyczk8q0ukaNvmogmJniEh1ztN6aYKTyU7cICj+rIVAzAZpuuBqM+m3AVEGDtpRklPDhaxlPNrb3J6K+uzcB8J7K50FZlQRLPDx4NYbN441pmPCsTm1zHI7gxO7fXCEYJgQqOzRvIYOIHaRsvkDKpTaU6njiVc4jcHQtH9XbknLxLDhmhIYUxlYGISj7JzCH+doHt7LaI+JAYp2deR60Lu/QB2btt7RigLSWBt3BTEhBtrf6gEe1yJqcw2QL5lkqX7OxB7rYdNEN1+VxFurktf1QHbzUIq0m4cb7V+mtzBsXFyBRalZnLHUmuLAhr761mc77NlJvgF0OdNK5HqlCvb3TOpCOFM9mJJXi7GODjJbeSn5hRp0KD3ApeD1bhQXTcesnl+tLdslq4H+6/aoIcD7vJw8bAo4b8oO10I//+/NcyJ+dEsvda7w==
    rootPassword: AgCa3kh04p0Ah0lRcbAeN0iTxo9f2nOIJp75U0ILkgOMMN4by73+BbpRNiRTxbvutPAc2WBhAlSpFHOdZxWfKGb3zDuqNvpWo5rBl1h/TrSt/tBEpjQ4OurBv8updsB92esf1EcSf2cU7LkgiDGR6fhW1I9tdEDKDJG3ONsmhX9mb9K8z0Q6dhKP4eb7q09MadpTkT2Y1uB8wBjzr88WD6ItoSHRA+sN9A9kYQH3E6VBm8Yv78gxafckRhbzWV/70umgJ8xujMhOK86A0QbW0vA3D99zFWDosuZ9tFnApm7IE4wyQWg8CLWbQsEXiIMEXB/r5z19+97tAyABA33rVEH5NMDgVT6zSP4vrdRpvbZHv6Z5hJSK+fRcAxT4p+dNsMIxiCBrknhPIYohYHRJQKUFbMVlCj6fmT/uF1SY6r9nOKj0a8R9YFizcj8kkdFxvQmqkn3ixszVc84+4YD60t4DRfStt9STaEt5mF9Z0cjDteUGqFvvRkph89Q5eUJPyPIAP6TlSNRelVOuTrC0Cc7vqUZ13n2Z6dHVHjEXmx4m/4kP6szA5VAuK4jCeE5xcr8awyA/P6oYQRbM7bvlk26l2RO3JK+fqW3NU+r7ACPsfEIJtAarPv3UoNRke5CQva7Kp4of7vqy9wJDD0ZkDjJQFEB/AvX4iiPgEE6bdIgUHglYtyL5MdBcVgc/FbVaR8ze6tyars06467wAGI=
    username: AgB7o5YfLb3+c4AT/IovX6zUVHiRdgmZovovDeXk2KKxSBK0BXm2BTGSyNqtthUoxVgN6/w/9VvjakTn1s/QDgJ1Ttduamp7zDSweb93vSbrQ0aBrStdNXOuzN2ukpS8E4X1Rx+oY4OkIDYpk/QhqDN4P+tT8QydT5Yp1wq6x03xgDrO7n250w3ST+Ra2LnK9llmjNPUz6zbOpGgZRxRbb7UcEBS2zsMY5dTc1mfccAXMJ7Zn9FobO+JgUyPoQngAjlSeT84QuvrUhRPEYdmEKtRlmGhFdk+XKTVW5WJMvgAPZIEn/KiupIYSCMcAiHyWYBQYLgjiiXvaGKPjjF3jvHIp1M6fi91xnulKFhwerHNa4M9/Ez05yAz5LTHmq63PHhX46PrDP57lLGVPDGBezNvQRlkywRjDxlqoTONdyMr2rjaa32pjC6wl/4J/GOjkjBetFeH9z79K45faRCG4nI0o7jdIbSFJtLSZrTJBwzkXEb6V2lO5hs5dp10S3H/yewZUDFnhBjRRHHs1PSIF45yCUyS+Mpt5R0/lLaCMWnhLdQjxtr1qNJbwIYmoFGXLunLl+y8WG+XhZZYzrTM/1QBVeZ/ZvMLexCqhqnwjz5RENQhzPfr3NPTczR2sYRtUladTbb8Z3v08M73y6XnO7LyWNzI+A0f9kxmcmV9eS767AnGEW4XNWNMDekdX4ngDHID6g7z
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: test-my.workstation.co.uk
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 100
  maxUnavailable: 1
  targetCPUUtilizationPercentage: 80