---
######################################################
# Configmaps: Create Multiples Configmaps data
######################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service_name }}-bootstrap-cm-apache2-{{ .Values.targetEnv }}
data:
    bootstrap-apache2.sh: |
        #!/bin/bash
        set -x
        FILE=/etc/resolv.conf
        echo "Workstation On Starting Pod Bootstrap Script"
            # Set DNS to cloudflare Name servers for faster DNS resolution
        echo "nameserver 1.1.1.1" >> $FILE
        echo "nameserver 1.0.0.1" >> $FILE

        echo "Workstation Apache2 Bootstrap Script"
        echo "==========================="
            
        cp -r /src/* /var/www/html/
        chmod 755 -R /var/www/html/
        chown www-data:root -R /var/www/html/
        chmod 777 -R /var/www/html/writable/
        chmod 777 -R /var/www/html/writable/cache/
        chmod 777 -R /var/www/html/writable/session/

        cp /tmp/secrets/.env /var/www/html/.env
        FILE=/var/www/html/.env
        if test -f "$FILE"; then
            echo "$FILE exists."
            echo "==========================="
            echo "Workstation Bootstrap Script Copied"
            echo "==========================="
        fi
            echo "Starting Workstation"
            echo "==========================="
            php -v
        echo "==========================="
        export COMPOSER_ALLOW_SUPERUSER=1
        yes | composer update
        chmod 777 -R /var/www/html/writable/
        chmod 777 -R /var/www/html/writable/cache/
        chmod 777 -R /var/www/html/writable/session/
        APP_RELEASE_NOTES_DOC_URL="https://webimpetus.cloud/docs/"
        export APP_RELEASE_NOTES_DOC_URL=$APP_RELEASE_NOTES_DOC_URL
        DATE_GEN_VERSION=$(date +"%Y%m%d%I%M%S")
        export DATE_GEN_VERSION=$(date +"%Y%m%d%I%M%S")
        echo APP_DEPLOYED_AT=$DATE_GEN_VERSION >> $FILE
        echo APP_ENVIRONMENT="{{ .Values.targetEnv }}" >> $FILE
        echo APP_RELEASE_NOTES_DOC_URL=$APP_RELEASE_NOTES_DOC_URL >> $FILE
        echo DYNAMIC_SCRIPTS_PATH=/tmp >> $FILE
        echo "==========================="
        echo "Copy apache config file for Workstation"
        cp /tmp/configmap/workstation.conf /etc/apache2/sites-available/000-default.conf
        echo "==========================="
        echo "Restart apache2"
        apachectl graceful
        php spark migrate
        #apachectl restart
        # a2ensite 000-default
        # service apache2 reload
        echo "==========================="
        echo "Workstation Apache2 Bootstrap Script Completed"   
    workstation.conf: |
        <VirtualHost *:80>
            ServerAdmin webmaster@localhost
            DocumentRoot /var/www/html/public
            DirectoryIndex index.html index.php
            ServerName {{ .Values.targetEnv }}-my.workstation.co.uk
                <Directory /var/www/html/public>
                        AllowOverride all
                </Directory>
        </VirtualHost>
        ServerName 127.0.0.1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service_name }}-bootstrap-cm-openresty-{{ .Values.targetEnv }}
#   namespace: {{ .Values.targetNS }}
data:
    bootstrap-openresty.sh: |
        #!/bin/bash
        set -x
        FILE=/etc/resolv.conf
        echo "Workstation On Starting Pod Bootstrap Script"
            # Set DNS to cloudflare Name servers for faster DNS resolution
        echo "nameserver 1.1.1.1" >> $FILE
        echo "nameserver 1.0.0.1" >> $FILE

        echo "Workstation Nginx Bootstrap Script"
        export COMPOSER_ALLOW_SUPERUSER=1
        yes | composer update
        echo "==========================="
        FILE=/src/
        if [ -d "$FILE" ]; then
        FILE=/var/www/html/
        cp -r /src/* $FILE
        if [ -d "$FILE" ]; then
        chmod 755 -R $FILE
        chown www-data:root -R $FILE
        chmod 777 -R ${FILE}writable/
        chmod 777 -R ${FILE}writable/cache/
        chmod 777 -R ${FILE}writable/session/

        cp /tmp/secrets/.env $FI    LE.env
        FILE=/var/www/html/.env
        if [ -f "$FILE" ];then
            echo "$FILE exists."
            echo "==========================="
            echo "Workstation Bootstrap Script Copied"
            echo "==========================="
        fi
            echo "Starting Workstation"
            echo "==========================="
            php -v
        echo "==========================="
        echo "Workstation Src copy to /var/www/html Complete"
        fi
        fi
        
        FILE=/var/www/html/writable/
        if [ -d "$FILE" ]; then
            echo "$FILE exists."
            chmod 777 -R $FILE
        fi
        FILE=/var/www/html/writable/cache/
        if [ -d "$FILE" ]; then
            echo "$FILE exists."
            chmod 777 -R $FILE
        fi
        FILE=/var/www/html/writable/session/
        if [ -d "$FILE" ]; then
            echo "$FILE exists."
            chmod 777 -R $FILE
        fi                
        APP_RELEASE_NOTES_DOC_URL="https://webimpetus.cloud/docs/"
        export APP_RELEASE_NOTES_DOC_URL=$APP_RELEASE_NOTES_DOC_URL
        DATE_GEN_VERSION=$(date +"%Y%m%d%I%M%S")
        export DATE_GEN_VERSION=$(date +"%Y%m%d%I%M%S")
        FILE=/var/www/html/.env
        echo APP_DEPLOYED_AT=$DATE_GEN_VERSION >> $FILE
        echo APP_ENVIRONMENT="{{ .Values.targetEnv }}" >> $FILE
        echo APP_RELEASE_NOTES_DOC_URL=$APP_RELEASE_NOTES_DOC_URL >> $FILE
        echo DYNAMIC_SCRIPTS_PATH=/tmp >> $FILE
        echo "==========================="
        echo "Copy openresty config file for Workstation"
        cp /tmp/configmap/workstation.conf /etc/nginx/sites-enabled/workstation.conf
        echo "==========================="
        echo "Restart openresty nginx"
        openresty -s reload
        php spark migrate
        echo "==========================="
        echo "Workstation Nginx Bootstrap Script Completed"      
    workstation.conf: |
        # Enter nginx config server block here later
