---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wsl-{{ .Values.targetEnv }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wsl-{{ .Values.targetEnv }}
  template:
    metadata:
      labels:
        app: wsl-{{ .Values.targetEnv }}
    spec:
      volumes:
        - name: wsl-boostrap-cm-vol
          # Populate the volume with config map data
          configMap:
            # `name` here must match the name 
            # specified in the ConfigMap's YAML 
            name: wsl-boostrap-cm-{{ .Values.targetEnv }}
        - name: wsl-env-vol-{{ .Values.targetEnv }}
          secret:
            secretName: wsl-secret-{{ .Values.targetEnv }}
            items:
            - key: env_file
              path: .env

      containers:
        - name: wsl-{{ .Values.targetEnv }}
          image: {{ .Values.targetImage }}:{{ .Values.targetImageTag }}
          ports:
            - containerPort: 80
          env:
            - name: "APACHE_CONFDIR"
              value: "/etc/apache2"
            - name: "APACHE_DOCUMENT_ROOT"
              value: "/var/www/html/public"
            - name: "APACHE_ENVVARS"
              value: "/etc/apache2/envvars"
            - name: "APACHE_RUN_DIR"
              value: "/var/run/apache2"
            - name: DYNAMIC_SCRIPTS_PATH
              value: "/var/www/html/writable/"
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "stat -c %a /tmp && ls -la /tmp && cp /tmp/configmap/wsl-bootstrap.sh /usr/local/bin/wsl-bootstrap.sh && chmod +x /usr/local/bin/wsl-bootstrap.sh && sh /usr/local/bin/wsl-bootstrap.sh"]
          volumeMounts:
            - name: wsl-env-vol-{{ .Values.targetEnv }}
              mountPath: /tmp/secrets
              # `bootstrap` mount bash script from configmap wsl-boostrap-cm-{{ .Values.targetEnv }}
              # execute in the poststrat lifecycle hook
            - name: wsl-boostrap-cm-vol
              mountPath: /tmp/configmap
              