######################################################
# Secret: Create Multiples encripted data
######################################################
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wsl-secret-{{ .Values.targetEnv }}
  namespace: {{ .Values.targetNameSpace }}
spec:
  encryptedData:
    env_file: {{ .Values.safeSealedSecret }}
  template:
    metadata:
      name: wsl-secret-{{ .Values.targetEnv }}
      namespace: {{ .Values.targetNameSpace }}
