---
apiVersion: v1
kind: Service
metadata:
  name: wsl-nodeport-{{ .Values.targetEnv }}
spec:
  selector:
    app: wsl-{{ .Values.targetEnv }}
  ports:
    - port: 80
      targetPort: 80
      nodePort: {{ .Values.svcAccessPort }}
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: wsl-svc-{{ .Values.targetEnv }}
spec:
  selector:
    app: wsl-{{ .Values.targetEnv }}
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
