# .github/workflows/deploy.yml
# TARGET_ENV is env variable as well as passed as steps var so troubleshoot carefully
name: Deploy Workstation CRM to Kubernetes

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      TARGET_ENV:
        type: choice
        description: 'Please choose the environment'
        default: 'test'
        required: true
        options:
          - dev
          - test
          - acc
          - prod

      TARGET_INFRA_PROVIDER:
        type: choice
        description: 'Please choose the environment'
        default: 'aws'
        required: true
        options:
          - aws
          - azure
          - namecheap
env:
  TARGET_ENV: ${{ inputs.TARGET_ENV }}
  TARGET_INFRA_PROVIDER: ${{ inputs.TARGET_INFRA_PROVIDER }}
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_TAG: ${{ github.ref_name }}
  TARGET_STACK: openresty_php
  IMAGE_NAME: webimpetus

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:

    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: short-sha
      uses: benjlevesque/short-sha@v1.2
      with:
        length: 6

    - run: echo $SHA
      env:
       SHA: ${{ steps.short-sha.outputs.sha }}

    - run: echo $SHA
      env:
       SHA: ${{ env.SHA }}

    - name: Init undefined variables to the default values
      run: |
        if [ $TARGET_ENV == "" ]; then
        echo "TARGET_ENV=test" >> $GITHUB_ENV
        fi
        
    - name: Build, tag, and push image to Workstation Docker Registry
      run: |
        docker build -f $(pwd)/devops/docker/Dockerfile --build-arg TAG=latest -t wsl-${{ env.TARGET_STACK }} . --no-cache
        docker tag wsl-${{ env.TARGET_STACK }} registry.workstation.co.uk/wsl-${{ env.TARGET_STACK }}:${{ env.SHA }}
        docker push registry.workstation.co.uk/wsl-${{ env.TARGET_STACK }}:${{ env.SHA }}

    - name: Helm Deploy - Release
      uses: koslib/helm-eks-action@master
      env:
        TARGET_ENV: ${{ env.TARGET_ENV }}
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        #command: helm delete wsl-$TARGET_ENV -n $TARGET_ENV
        command: helm upgrade -i wsl-${{ env.TARGET_ENV }} ./devops/webimpetus-chart -f devops/webimpetus-chart/values-${{ env.TARGET_ENV }}.yaml --set-string targetImage="registry.workstation.co.uk/wsl-${{ env.TARGET_STACK }}" --set-string targetImageTag="${{ env.SHA }}" --namespace ${{ env.TARGET_ENV }}

    - uses: actions-hub/kubectl@master
      env:
        TARGET_ENV: ${{ env.TARGET_ENV }}
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: rollout restart deployment/wsl-${{ env.TARGET_ENV }} -n ${{ env.TARGET_ENV }}

    - uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: get pods -A

    - name: Slack Notification for Workstation CRM release 
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: general
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Post Content :rocket:'
        SLACK_TITLE: Post Title
        SLACK_USERNAME: rtCamp
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
